### ISSUE TITLE
NeoSectional not working after latest Stretch update 

### ISSUE THREAD

**Issue by freilichr** [JJSilva/NeoSectional#1]
After getting the latest update of Stretch Lite, I began the installation of jgraff's rpi_ws281x.  Running **sudo python setup.py install** in /rpi_281x/python, there were a lot of errors.  (see https://github.com/jgarff/rpi_ws281x/issues/290)

Extracting in /tmp/tmpejd0zm
Traceback (most recent call last):
File "./setup.py", line 4, in 
use_setuptools()
File "/home/pi/libs/rpi_ws281x/python/ez_setup.py", line 140, in use_setuptools
return _do_download(version, download_base, to_dir, download_delay)
File "/home/pi/libs/rpi_ws281x/python/ez_setup.py", line 120, in _do_download
_build_egg(egg, archive, to_dir)
File "/home/pi/libs/rpi_ws281x/python/ez_setup.py", line 62, in _build_egg
with archive_context(archive_filename):
File "/usr/lib/python2.7/contextlib.py", line 17, in enter
return self.gen.next()
File "/home/pi/libs/rpi_ws281x/python/ez_setup.py", line 100, in archive_context
with ContextualZipFile(filename) as archive:
File "/home/pi/libs/rpi_ws281x/python/ez_setup.py", line 88, in new
return zipfile.ZipFile(*args, **kwargs)
File "/usr/lib/python2.7/zipfile.py", line 770, in init
self._RealGetContents()
File "/usr/lib/python2.7/zipfile.py", line 813, in _RealGetContents
raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

The workaround was 
sudo apt-get install python-pip
sudo pip install rpi_ws281x
python ./setup.py build

This may have helped run ... python/examples/strandtest.py but metar.py would still not run.  Can you help me sort this out?  Thanks

**Comment by JJSilva** [comment]
I noticed the last few lines of output said zipfile.BadZipfile
Perhaps an something is wrong with that zip file. 

If not whats the output of the metar.py?

**Comment by freilichr** [comment]
The rpi_ws281x library is now a PIP install as far as I can tell.  Not sure exactly what changed (relative noob) except scons and manual setup.py install are no longer required after using PIP.  NeoSectional works fine now that ws281x library install has been sorted.  Thanks!
